# Generated by Django 5.1.7 on 2025-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano_pub', models.DateField(blank=True, null=True)),
                ('editora', models.CharField(blank=True, max_length=100, null=True)),
                ('idioma', models.CharField(default='portugues', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
