# Generated by Django 5.1.7 on 2025-03-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='biblioteca',
            new_name='Livro',
        ),
    ]
