# Generated by Django 5.1.6 on 2025-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateField()),
                ('local', models.TextField(blank=True, null=True)),
                ('Categoria', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
