# Generated by Django 5.1.7 on 2025-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_eventos', '0002_rename_user_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_hora',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
